// Code generated by protoc-gen-go.
// source: log_it.proto
// DO NOT EDIT!

/*
Package proto is a generated protocol buffer package.

It is generated from these files:
	log_it.proto

It has these top-level messages:
	LogData
	LogSuccess
*/
package proto

import proto1 "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto1.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto1.ProtoPackageIsVersion2 // please upgrade the proto package

type LogData struct {
	Severity int32  `protobuf:"varint,1,opt,name=severity" json:"severity,omitempty"`
	Data     string `protobuf:"bytes,2,opt,name=data" json:"data,omitempty"`
}

func (m *LogData) Reset()                    { *m = LogData{} }
func (m *LogData) String() string            { return proto1.CompactTextString(m) }
func (*LogData) ProtoMessage()               {}
func (*LogData) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *LogData) GetSeverity() int32 {
	if m != nil {
		return m.Severity
	}
	return 0
}

func (m *LogData) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

type LogSuccess struct {
	Status string `protobuf:"bytes,1,opt,name=status" json:"status,omitempty"`
	Msg    string `protobuf:"bytes,2,opt,name=msg" json:"msg,omitempty"`
}

func (m *LogSuccess) Reset()                    { *m = LogSuccess{} }
func (m *LogSuccess) String() string            { return proto1.CompactTextString(m) }
func (*LogSuccess) ProtoMessage()               {}
func (*LogSuccess) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *LogSuccess) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *LogSuccess) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func init() {
	proto1.RegisterType((*LogData)(nil), "proto.LogData")
	proto1.RegisterType((*LogSuccess)(nil), "proto.LogSuccess")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for LogIt service

type LogItClient interface {
	// just log some data
	LogMessage(ctx context.Context, in *LogData, opts ...grpc.CallOption) (*LogSuccess, error)
}

type logItClient struct {
	cc *grpc.ClientConn
}

func NewLogItClient(cc *grpc.ClientConn) LogItClient {
	return &logItClient{cc}
}

func (c *logItClient) LogMessage(ctx context.Context, in *LogData, opts ...grpc.CallOption) (*LogSuccess, error) {
	out := new(LogSuccess)
	err := grpc.Invoke(ctx, "/proto.LogIt/LogMessage", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for LogIt service

type LogItServer interface {
	// just log some data
	LogMessage(context.Context, *LogData) (*LogSuccess, error)
}

func RegisterLogItServer(s *grpc.Server, srv LogItServer) {
	s.RegisterService(&_LogIt_serviceDesc, srv)
}

func _LogIt_LogMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LogData)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LogItServer).LogMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.LogIt/LogMessage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LogItServer).LogMessage(ctx, req.(*LogData))
	}
	return interceptor(ctx, in, info, handler)
}

var _LogIt_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.LogIt",
	HandlerType: (*LogItServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "LogMessage",
			Handler:    _LogIt_LogMessage_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "log_it.proto",
}

func init() { proto1.RegisterFile("log_it.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 204 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x44, 0x8e, 0x31, 0x4b, 0xc4, 0x40,
	0x10, 0x85, 0x5d, 0x35, 0xa7, 0x37, 0x88, 0xe8, 0x14, 0xc7, 0x91, 0x2a, 0xa4, 0x90, 0x54, 0x0b,
	0x2a, 0x08, 0x5a, 0x06, 0x1b, 0x21, 0x42, 0x88, 0x3f, 0x40, 0xd6, 0xb8, 0x0c, 0x0b, 0x09, 0x13,
	0x32, 0x13, 0xd1, 0x7f, 0x2f, 0x59, 0x17, 0xaf, 0x9a, 0xf7, 0x15, 0xdf, 0x9b, 0x07, 0x17, 0x03,
	0xd3, 0x7b, 0x50, 0x3b, 0xcd, 0xac, 0x8c, 0x59, 0x3c, 0xe5, 0x23, 0x9c, 0x35, 0x4c, 0xcf, 0x4e,
	0x1d, 0xe6, 0x70, 0x2e, 0xfe, 0xcb, 0xcf, 0x41, 0x7f, 0xf6, 0xa6, 0x30, 0x55, 0xd6, 0xfd, 0x33,
	0x22, 0x9c, 0x7e, 0x3a, 0x75, 0xfb, 0xe3, 0xc2, 0x54, 0xdb, 0x2e, 0xe6, 0xf2, 0x01, 0xa0, 0x61,
	0x7a, 0x5b, 0xfa, 0xde, 0x8b, 0xe0, 0x0e, 0x36, 0xa2, 0x4e, 0x17, 0x89, 0xee, 0xb6, 0x4b, 0x84,
	0x57, 0x70, 0x32, 0x0a, 0x25, 0x71, 0x8d, 0x77, 0x4f, 0x90, 0x35, 0x4c, 0x2f, 0x8a, 0xb7, 0xb1,
	0xe0, 0xd5, 0x8b, 0x38, 0xf2, 0x78, 0xf9, 0x37, 0xcc, 0xa6, 0x39, 0xf9, 0xf5, 0x81, 0xd3, 0x8f,
	0xf2, 0xa8, 0xbe, 0x81, 0x5d, 0x60, 0x4b, 0xf3, 0xd4, 0x5b, 0xff, 0xed, 0xc6, 0x69, 0xf0, 0x62,
	0x07, 0xa6, 0xa0, 0x35, 0xc4, 0xce, 0x76, 0x55, 0x5a, 0xf3, 0xb1, 0x89, 0xee, 0xfd, 0x6f, 0x00,
	0x00, 0x00, 0xff, 0xff, 0x6d, 0xb8, 0x3d, 0x14, 0xf4, 0x00, 0x00, 0x00,
}
